#!/bin/bash
#Author: Ali Sezişli (https://alisezisli.com.tr) (https://gnuadm.in)
#Exit Codes:
#0- Success
#1- Columns or rows are not positive integer

#Number regex:
number_regex='^[0-9]+$'

help()
{
	#Display help
    echo "help"
}
generate()
{
    printf "How many columns do you need?: "
    read columns
    printf "How many rows do you need?: "
    read rows
    if [[ ! ${columns} =~ ${number_regex} ]] || [[ ! ${rows} =~ ${number_regex} ]]; then
    echo "Columns and rows must be a positive integer."
    exit 1
    fi
}

declare -i arg_count=$#

if [ ${arg_count} -gt 999 ]; then
	printf "Too many arguments. Use help for more information.\n"
	exit
fi

case ${arg_count} in
	0)
		#Start interactive:
		;;
	1)
		#Only one argument:
		if [[ $1 == "help" ]]; then
        help
		elif [[ $1 == "generate" ]]; then
		#Generate interactive:
        generate
		fi
        ;;
esac